# Generated by Django 2.2.7 on 2022-06-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutName', models.CharField(max_length=100)),
                ('aboutUs', models.CharField(max_length=100)),
                ('aboutDescription', models.CharField(max_length=10000)),
            ],
        ),
    ]
