# Generated by Django 4.0.3 on 2022-06-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blogcard_alter_aboutcontent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcard',
            name='blogImg',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
