# Generated by Django 4.0.3 on 2022-06-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_blogcard_blogimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactHeader', models.CharField(max_length=100)),
                ('contactParagraph', models.CharField(max_length=1000)),
                ('contactName', models.CharField(max_length=100)),
                ('contactImg', models.ImageField(blank=True, upload_to='contact')),
                ('contactPosition', models.CharField(max_length=100)),
                ('contactPhone', models.CharField(max_length=100)),
                ('contactEmail', models.CharField(max_length=100)),
            ],
        ),
    ]
