# Generated by Django 4.0.3 on 2022-06-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactHeader', models.CharField(max_length=100)),
                ('contactParagraph', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='contactHeader',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='contactParagraph',
        ),
    ]
