# Generated by Django 3.2.9 on 2022-06-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contactpage_remove_contactdetails_contactheader_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderImg', models.ImageField(blank=True, upload_to='pics')),
                ('leaderName', models.CharField(max_length=100)),
                ('leaderPosition', models.CharField(max_length=100)),
                ('leaderDesc', models.CharField(max_length=1000)),
            ],
        ),
    ]
