# Generated by Django 3.2.9 on 2022-06-16 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_academic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academic',
            old_name='acadsdesc',
            new_name='acadsDesc',
        ),
    ]
