# Generated by Django 4.0.3 on 2022-06-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_acadsdesc_academic_acadsdesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraHeader', models.CharField(max_length=100)),
                ('extraImg', models.ImageField(blank=True, upload_to='extras')),
                ('extraParagraph', models.CharField(max_length=1000)),
                ('extraHref', models.CharField(max_length=1000)),
            ],
        ),
    ]
