# Generated by Django 2.2.7 on 2022-06-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogImg',
            field=models.ImageField(blank=True, upload_to='blogs'),
        ),
    ]
