# Generated by Django 2.2.7 on 2022-06-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_blog_blogimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=None, max_length=200, unique=True),
        ),
    ]
