# Generated by Django 2.2.7 on 2022-06-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20220619_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogGenre',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
