# Generated by Django 2.2.7 on 2022-07-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_blog_bloggenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='entry1href',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='entry1img',
            field=models.ImageField(blank=True, upload_to='events'),
        ),
        migrations.AddField(
            model_name='event',
            name='entry1name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='entry2href',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='entry2img',
            field=models.ImageField(blank=True, upload_to='events'),
        ),
        migrations.AddField(
            model_name='event',
            name='entry2name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='entry3href',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='entry3img',
            field=models.ImageField(blank=True, upload_to='events'),
        ),
        migrations.AddField(
            model_name='event',
            name='entry3name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
